### ISSUE TITLE
Move footer to the actual bottom of the view

### ISSUE THREAD

**Issue by alexander-bauer** [UMBC-CMSC447-Spring2017-Team5/college-JUMP#16]

**Comment by Mjacks3** [comment]
Hey  Sasha, I'm having an issue where none of my HTML changes are getting updated server side. I just updated the env (actually I reinstalled the env through the terminal to get sqlalchemy) and the site launches locally, but none of my code changes are getting  updated. Did I screw something up when I installed the env again?

**Comment by Mjacks3** [comment]
@alexander-bauer

**Comment by alexander-bauer** [comment]
@Mjacks3 I don't see any commits that have been pushed to GitHub, so it looks like either you haven't committed your changes, or you did commit them but never pushed them. I can help diagnose that if you've done those and they're not arriving on GitHub where I'm expecting them.

**Comment by ichniow1** [comment]
If this issue is just the footer location within theme.html, fixed it because I already had it open

**Comment by Mjacks3** [comment]
@ichniow1 ooh great, saves me some effort. If you wouldn't mind, could you sync it up?

**Comment by Mjacks3** [comment]
lol, I'm dumb, its already up. Thanks!

**Comment by Mjacks3** [comment]
Working with this issue is actually a lot more tedious than I thought. I'll re prioritize for the purpose of the UID for now and open it up for help. @ichniow1 the issue is to move the footer to the bottom of the page  page (moving the footer header in theme.html was actually good for organization's sake but the issue is moving the footer content so that it's at the bottom of the screen on any page on the website.) This was tricky with because the results keep acting differently on long vs short content pages.

**Comment by Mjacks3** [comment]
Done
