### ISSUE TITLE
Interface for editing users

### ISSUE THREAD

**Issue by Mjacks3** [UMBC-CMSC447-Spring2017-Team5/college-JUMP#40]
Multi-leveled- administrator and mentor/student side

**Comment by Mjacks3** [comment]
@alexander-bauer  so for this part I'm going to need to be able to lookup users in two ways. One is their own account interface when they get signed in so that they can change their information. The second is to be able to search for any user and pull their account info as an admin. I know the first should be relatively simple to pull off: I saw the code for that within some of the other form information. But do you know if its possible to somehow lookup all users and return their information through a form or something of the like? I'm gonna scour documentation tomorrow, but I was wondering if you knew what the best way to do what I'm trying to do would be.

**Comment by alexander-bauer** [comment]
@Mjacks3 

Probably the thing to do at this scale is to mass-lookup the user information within the context of the view function using `models.User.query()` and pass the resulting generator to the template (via `context`, but that's under the hood) as with `render_template(..., users=users_you_looked_up)`. Then, they'll be accessible as an iterable data structure, and you can loop through them to fill out the data in the view you want, like

```
{% for user in users %}
<li>{{user.name}}</li>
{% endfor %}
```

As a side node, sometimes you see `...query().all()`, and here's a [StackOverflow post](http://stackoverflow.com/questions/1078383/sqlalchemy-difference-between-querin the context map, as withy-and-query-all-in-for-loops) about how that differs from the one above. We probably want to use just `query()` rather than `query().all()`.

**Comment by Mjacks3** [comment]
done
