### ISSUE TITLE
Clean up and professionalize user interface

### ISSUE THREAD

**Issue by alexander-bauer** [UMBC-CMSC447-Spring2017-Team5/college-JUMP#75]

**Comment by alexander-bauer** [comment]
If there are no announcements to be shown, some muted text should say so. This could be done with `{% for ... %} {% else %} {% endfor %}`-style directives.

**Comment by Mjacks3** [comment]
Never mind, absolute sidnav is wonking out
![image](https://cloud.githubusercontent.com/assets/22308738/25729573/21376dda-3104-11e7-8480-62ffc59763de.png)

**Comment by Mjacks3** [comment]
So I think the problem is that the footer and sidnav correspond to different things and are blocked separately. The footer maps to the length of the body content and the sidnav maps to the amount of semesters it needs to display. Both have separate blocks/containers as well.
If the semesters we need to display have more content than in the body, this happens. I'm not sure if I know how to fix this without integrating some permutation of the {%mainbody%},{%footer%},and {%sidenav%}  blocks together. What do you think, @alexander-bauer ?

**Comment by alexander-bauer** [comment]
All of the glaring user interface issues are resolved, and everything conforms well to the Bootstrap standards. I don't think we're missing anything major that would hold up the demo, so I'm calling this complete.
